export const match = {
  matchID: 64085,
  matchDateTime: '2023-03-17T20:30:00',
  timeZoneID: 'W. Europe Standard Time',
  leagueId: 4562,
  leagueName: '1. Fußball-Bundesliga 2022/2023',
  leagueSeason: 2022,
  leagueShortcut: 'bl1',
  matchDateTimeUTC: '2023-03-17T19:30:00Z',
  group: {
    groupName: '25. Spieltag',
    groupOrderID: 25,
    groupID: 39905,
  },
  team1: {
    teamId: 87,
    teamName: 'Borussia Mönchengladbach',
    shortName: 'Gladbach',
    teamIconUrl: 'https://i.imgur.com/KSIk0Eu.png',
    teamGroupName: null,
  },
  team2: {
    teamId: 134,
    teamName: 'Werder Bremen',
    shortName: 'Bremen',
    teamIconUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SV-Werder-Bremen-Logo.svg/681px-SV-Werder-Bremen-Logo.svg.png',
    teamGroupName: null,
  },
  lastUpdateDateTime: '2023-03-17T22:26:17.563',
  matchIsFinished: true,
  matchResults: [
    {
      resultID: 102113,
      resultName: 'Endergebnis',
      pointsTeam1: 2,
      pointsTeam2: 2,
      resultOrderID: 1,
      resultTypeID: 2,
      resultDescription: 'Ergebnis nach Ende der offiziellen Spielzeit',
    },
    {
      resultID: 102114,
      resultName: 'Halbzeit',
      pointsTeam1: 0,
      pointsTeam2: 0,
      resultOrderID: 2,
      resultTypeID: 1,
      resultDescription: 'Zwischenstand zur Halbzeit',
    },
  ],
  goals: [
    {
      goalID: 100531,
      scoreTeam1: 1,
      scoreTeam2: 1,
      matchMinute: 65,
      goalGetterID: 18422,
      goalGetterName: 'M. Ducksch',
      isPenalty: false,
      isOwnGoal: false,
      isOvertime: false,
      comment: null,
    },
    {
      goalID: 100533,
      scoreTeam1: 2,
      scoreTeam2: 2,
      matchMinute: 89,
      goalGetterID: 18422,
      goalGetterName: 'M. Ducksch',
      isPenalty: false,
      isOwnGoal: false,
      isOvertime: false,
      comment: null,
    },
    {
      goalID: 100530,
      scoreTeam1: 1,
      scoreTeam2: 0,
      matchMinute: 48,
      goalGetterID: 18573,
      goalGetterName: 'M. Thuram',
      isPenalty: false,
      isOwnGoal: false,
      isOvertime: false,
      comment: null,
    },
    {
      goalID: 100532,
      scoreTeam1: 2,
      scoreTeam2: 1,
      matchMinute: 73,
      goalGetterID: 18655,
      goalGetterName: 'F. Neuhaus',
      isPenalty: false,
      isOwnGoal: false,
      isOvertime: false,
      comment: null,
    },
  ],
  location: {
    locationID: 32,
    locationCity: 'Mönchengladbach',
    locationStadium: 'Borussia Park',
  },
  numberOfViewers: null,
}
