// SETUP USER
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_USER_BETS = 'GET_USER_BETS'
// LOGOUT
export const LOGOUT_USER = 'LOGOUT_USER'
// ALERT
export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CREATE_BET_SUCCESS = 'CREATE_BET_SUCCESS'
// BUNDESLIGA MATCHES
export const SET_BUNDESLIGA_MATCHES = 'SET_BUNDESLIGA_MATCHES'
export const GET_LEADERBOARD = 'GET_LEADERBOARD'
